# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Test_Rohan
                                 A QGIS plugin
 A plugin that uploads and visualizes point, line, and polygon shapefiles


 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-15
        copyright            : (C) 2025 by Rohan Patil
        email                : rohanpatil4002@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Test_Rohan class from file Test_Rohan.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .test_rohan import Test_Rohan
    return Test_Rohan(iface)
